seed: 42
device: cuda:0
num_steps_per_env: 24
max_iterations: 8000
empirical_normalization: false
policy:
  class_name: ActorCritic
  init_noise_std: 1.0
  actor_hidden_dims:
  - 128
  - 128
  - 128
  critic_hidden_dims:
  - 128
  - 128
  - 128
  activation: elu
algorithm:
  class_name: PPOSymmDataAugmented
  value_loss_coef: 1.0
  use_clipped_value_loss: true
  clip_param: 0.2
  entropy_coef: 0.005
  num_learning_epochs: 5
  num_mini_batches: 4
  learning_rate: 0.001
  schedule: fixed
  gamma: 0.99
  lam: 0.95
  desired_kl: 0.01
  max_grad_norm: 1.0
save_interval: 50
experiment_name: aliengo_rough_direct
run_name: ''
logger: wandb
neptune_project: aliengo-basic-rl
wandb_project: aliengo-basic-rl
resume: false
load_run: .*
load_checkpoint: model_.*.pt
amp_data_path: /home/iit.local/gturrisi/personal_ws_home/Quadruped-PyMPC/
dataset_names:
- traj_0
- traj_1
- traj_2
- traj_3
dataset_weights:
- 1.0
- 1.0
- 1.0
- 1.0
slow_down_factor: 1.0
discriminator:
  class_name: Discriminator
  hidden_dims:
  - 1024
  - 512
  reward_scale: 1.0
morphologycal_symmetries_cfg:
  class_name: MorphologycalSymmetries
  obs_space_names:
  - base_lin_vel:base
  - base_ang_vel:base
  - gravity:base
  - ctrl_commands
  - default_qpos_js_error
  - qvel_js
  - actions
  - clock_data
  action_space_names:
  - actions
  joints_order:
  - FL_hip_joint
  - FR_hip_joint
  - RL_hip_joint
  - RR_hip_joint
  - FL_thigh_joint
  - FR_thigh_joint
  - RL_thigh_joint
  - RR_thigh_joint
  - FL_calf_joint
  - FR_calf_joint
  - RL_calf_joint
  - RR_calf_joint
  history_length: 5
  robot_name: a1
