name: basic_locomotion_dls_isaaclab_ros2_env
channels:
- conda-forge
- nvidia
- robostack-staging
dependencies:
- pip
- python
- numpy
- cuda-nvcc 
- ros-humble-desktop
- ros-noetic-plotjuggler-ros
- compilers 
- cmake 
- pkg-config 
- make 
- ninja 
- colcon-common-extensions 
- catkin_tools 
- rosdep
- tqdm
- gymnasium
- pip:
  - readchar
  - onnxruntime
  - torch
  - gym-quadruped